name: Autograding Tests

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Week 1: Level 1
        id: level1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: 'Level 1'
          command: 'vendor/bin/phpunit level1/tests/Level1Test.php'
          timeout: '5'
          max-score: '1'

      - name: Week 2: Level 2
        id: level2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: 'Level 2'
          command: 'vendor/bin/phpunit level2/tests/Level2Test.php'
          timeout: '5'
          max-score: '1'

      - name: Week 3: Level 3
        id: level3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: 'Level 3'
          command: 'vendor/bin/phpunit level3/tests/Level3Test.php'
          timeout: '5'
          max-score: '1'

      - name: Week 4: Level 4
        id: level4
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: 'Level 4'
          command: 'vendor/bin/phpunit level4/tests/Level4Test.php'
          timeout: '5'
          max-score: '1'

      - name: Week 5: Level 5
        id: level5
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: 'Level 5'
          command: 'vendor/bin/phpunit level5/tests/Level5Test.php'
          timeout: '5'
          max-score: '1'

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          LEVEL1_RESULTS: "${{steps.level1.outputs.result}}"
          LEVEL2_RESULTS: "${{steps.level2.outputs.result}}"
          LEVEL3_RESULTS: "${{steps.level3.outputs.result}}"
          LEVEL4_RESULTS: "${{steps.level4.outputs.result}}"
          LEVEL5_RESULTS: "${{steps.level5.outputs.result}}"
        with:
          runners: level1,level2,level3,level4,level5